/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ApplicationService } from "../application.service";
import { ApplicationCreateInput } from "./ApplicationCreateInput";
import { Application } from "./Application";
import { ApplicationFindManyArgs } from "./ApplicationFindManyArgs";
import { ApplicationWhereUniqueInput } from "./ApplicationWhereUniqueInput";
import { ApplicationUpdateInput } from "./ApplicationUpdateInput";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { DocumentWhereUniqueInput } from "../../document/base/DocumentWhereUniqueInput";
import { EducationFindManyArgs } from "../../education/base/EducationFindManyArgs";
import { Education } from "../../education/base/Education";
import { EducationWhereUniqueInput } from "../../education/base/EducationWhereUniqueInput";
import { TrainingFindManyArgs } from "../../training/base/TrainingFindManyArgs";
import { Training } from "../../training/base/Training";
import { TrainingWhereUniqueInput } from "../../training/base/TrainingWhereUniqueInput";
import { WorkExperienceFindManyArgs } from "../../workExperience/base/WorkExperienceFindManyArgs";
import { WorkExperience } from "../../workExperience/base/WorkExperience";
import { WorkExperienceWhereUniqueInput } from "../../workExperience/base/WorkExperienceWhereUniqueInput";

export class ApplicationControllerBase {
  constructor(protected readonly service: ApplicationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Application })
  async createApplication(
    @common.Body() data: ApplicationCreateInput
  ): Promise<Application> {
    return await this.service.createApplication({
      data: {
        ...data,

        institution: data.institution
          ? {
              connect: data.institution,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        applicationNumber: true,
        comments: true,
        createdAt: true,
        id: true,

        institution: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Application] })
  @ApiNestedQuery(ApplicationFindManyArgs)
  async applications(@common.Req() request: Request): Promise<Application[]> {
    const args = plainToClass(ApplicationFindManyArgs, request.query);
    return this.service.applications({
      ...args,
      select: {
        applicationNumber: true,
        comments: true,
        createdAt: true,
        id: true,

        institution: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Application })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async application(
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<Application | null> {
    const result = await this.service.application({
      where: params,
      select: {
        applicationNumber: true,
        comments: true,
        createdAt: true,
        id: true,

        institution: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Application })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateApplication(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() data: ApplicationUpdateInput
  ): Promise<Application | null> {
    try {
      return await this.service.updateApplication({
        where: params,
        data: {
          ...data,

          institution: data.institution
            ? {
                connect: data.institution,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          applicationNumber: true,
          comments: true,
          createdAt: true,
          id: true,

          institution: {
            select: {
              id: true,
            },
          },

          status: true,
          submissionDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Application })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteApplication(
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<Application | null> {
    try {
      return await this.service.deleteApplication({
        where: params,
        select: {
          applicationNumber: true,
          comments: true,
          createdAt: true,
          id: true,

          institution: {
            select: {
              id: true,
            },
          },

          status: true,
          submissionDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/documents")
  @ApiNestedQuery(DocumentFindManyArgs)
  async findDocuments(
    @common.Req() request: Request,
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<Document[]> {
    const query = plainToClass(DocumentFindManyArgs, request.query);
    const results = await this.service.findDocuments(params.id, {
      ...query,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fileUrl: true,
        id: true,
        title: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verified: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/documents")
  async connectDocuments(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        connect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/documents")
  async updateDocuments(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        set: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/documents")
  async disconnectDocuments(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        disconnect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/educations")
  @ApiNestedQuery(EducationFindManyArgs)
  async findEducations(
    @common.Req() request: Request,
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<Education[]> {
    const query = plainToClass(EducationFindManyArgs, request.query);
    const results = await this.service.findEducations(params.id, {
      ...query,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        degree: true,
        fieldOfStudy: true,
        graduationYear: true,
        id: true,
        institutionName: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/educations")
  async connectEducations(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: EducationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      educations: {
        connect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/educations")
  async updateEducations(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: EducationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      educations: {
        set: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/educations")
  async disconnectEducations(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: EducationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      educations: {
        disconnect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/trainings")
  @ApiNestedQuery(TrainingFindManyArgs)
  async findTrainings(
    @common.Req() request: Request,
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<Training[]> {
    const query = plainToClass(TrainingFindManyArgs, request.query);
    const results = await this.service.findTrainings(params.id, {
      ...query,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        certificateNumber: true,
        completionDate: true,
        createdAt: true,
        id: true,
        provider: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trainings")
  async connectTrainings(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: TrainingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainings: {
        connect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trainings")
  async updateTrainings(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: TrainingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainings: {
        set: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trainings")
  async disconnectTrainings(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: TrainingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainings: {
        disconnect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/workExperiences")
  @ApiNestedQuery(WorkExperienceFindManyArgs)
  async findWorkExperiences(
    @common.Req() request: Request,
    @common.Param() params: ApplicationWhereUniqueInput
  ): Promise<WorkExperience[]> {
    const query = plainToClass(WorkExperienceFindManyArgs, request.query);
    const results = await this.service.findWorkExperiences(params.id, {
      ...query,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        employerName: true,
        endDate: true,
        id: true,
        position: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/workExperiences")
  async connectWorkExperiences(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: WorkExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workExperiences: {
        connect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/workExperiences")
  async updateWorkExperiences(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: WorkExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workExperiences: {
        set: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/workExperiences")
  async disconnectWorkExperiences(
    @common.Param() params: ApplicationWhereUniqueInput,
    @common.Body() body: WorkExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workExperiences: {
        disconnect: body,
      },
    };
    await this.service.updateApplication({
      where: params,
      data,
      select: { id: true },
    });
  }
}
