/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Training } from "./Training";
import { TrainingCountArgs } from "./TrainingCountArgs";
import { TrainingFindManyArgs } from "./TrainingFindManyArgs";
import { TrainingFindUniqueArgs } from "./TrainingFindUniqueArgs";
import { CreateTrainingArgs } from "./CreateTrainingArgs";
import { UpdateTrainingArgs } from "./UpdateTrainingArgs";
import { DeleteTrainingArgs } from "./DeleteTrainingArgs";
import { Application } from "../../application/base/Application";
import { User } from "../../user/base/User";
import { TrainingService } from "../training.service";
@graphql.Resolver(() => Training)
export class TrainingResolverBase {
  constructor(protected readonly service: TrainingService) {}

  async _trainingsMeta(
    @graphql.Args() args: TrainingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Training])
  async trainings(
    @graphql.Args() args: TrainingFindManyArgs
  ): Promise<Training[]> {
    return this.service.trainings(args);
  }

  @graphql.Query(() => Training, { nullable: true })
  async training(
    @graphql.Args() args: TrainingFindUniqueArgs
  ): Promise<Training | null> {
    const result = await this.service.training(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Training)
  async createTraining(
    @graphql.Args() args: CreateTrainingArgs
  ): Promise<Training> {
    return await this.service.createTraining({
      ...args,
      data: {
        ...args.data,

        application: args.data.application
          ? {
              connect: args.data.application,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Training)
  async updateTraining(
    @graphql.Args() args: UpdateTrainingArgs
  ): Promise<Training | null> {
    try {
      return await this.service.updateTraining({
        ...args,
        data: {
          ...args.data,

          application: args.data.application
            ? {
                connect: args.data.application,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Training)
  async deleteTraining(
    @graphql.Args() args: DeleteTrainingArgs
  ): Promise<Training | null> {
    try {
      return await this.service.deleteTraining(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Application, {
    nullable: true,
    name: "application",
  })
  async getApplication(
    @graphql.Parent() parent: Training
  ): Promise<Application | null> {
    const result = await this.service.getApplication(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Training): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
