/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Institution } from "./Institution";
import { InstitutionCountArgs } from "./InstitutionCountArgs";
import { InstitutionFindManyArgs } from "./InstitutionFindManyArgs";
import { InstitutionFindUniqueArgs } from "./InstitutionFindUniqueArgs";
import { CreateInstitutionArgs } from "./CreateInstitutionArgs";
import { UpdateInstitutionArgs } from "./UpdateInstitutionArgs";
import { DeleteInstitutionArgs } from "./DeleteInstitutionArgs";
import { ApplicationFindManyArgs } from "../../application/base/ApplicationFindManyArgs";
import { Application } from "../../application/base/Application";
import { User } from "../../user/base/User";
import { InstitutionService } from "../institution.service";
@graphql.Resolver(() => Institution)
export class InstitutionResolverBase {
  constructor(protected readonly service: InstitutionService) {}

  async _institutionsMeta(
    @graphql.Args() args: InstitutionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Institution])
  async institutions(
    @graphql.Args() args: InstitutionFindManyArgs
  ): Promise<Institution[]> {
    return this.service.institutions(args);
  }

  @graphql.Query(() => Institution, { nullable: true })
  async institution(
    @graphql.Args() args: InstitutionFindUniqueArgs
  ): Promise<Institution | null> {
    const result = await this.service.institution(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Institution)
  async createInstitution(
    @graphql.Args() args: CreateInstitutionArgs
  ): Promise<Institution> {
    return await this.service.createInstitution({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Institution)
  async updateInstitution(
    @graphql.Args() args: UpdateInstitutionArgs
  ): Promise<Institution | null> {
    try {
      return await this.service.updateInstitution({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Institution)
  async deleteInstitution(
    @graphql.Args() args: DeleteInstitutionArgs
  ): Promise<Institution | null> {
    try {
      return await this.service.deleteInstitution(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Application], { name: "applications" })
  async findApplications(
    @graphql.Parent() parent: Institution,
    @graphql.Args() args: ApplicationFindManyArgs
  ): Promise<Application[]> {
    const results = await this.service.findApplications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Institution): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
